Repository final-project-insider/FRONT-LOGIN, pull requests merged in 2024-05, with the labels that each got.

#6 feat #1 - [출퇴근] 출퇴근 조회
  package-lock.json
  package.json
  src/App.js
  src/Store.js
  src/apis/CommuteAPICalls.js
  src/components/Sidebar.js
  src/index.js
  src/modules/CommuteModule.js
  src/modules/index.js
  src/pages/Error.js
  src/pages/commute/CommuteCorrectionManage.js
  src/pages/commute/CommuteManage.js
  src/pages/commute/RecordCommute.js
  src/pages/commute/RecordCorrectionOfCommute.js
  src/pages/commute/commute.css
Labels: 🎈API, 💻Feature

#7 feat #1 - [캘린더] 일정 등록
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/apis/CalendarAPICalls.js
  src/components/Sidebar.js
  src/modules/CalendarModule.js
  src/modules/index.js
  src/pages/calendar/Calendar.css
  src/pages/calendar/Calendar.jsx
  src/pages/calendar/Modal.js
Labels: 🎈API, 💻Feature

#12 feat #2 - [공지사항] 공지사항 상세조회 / 파일 다운로드
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/apis/other/announce/AncAPICalls.js
  src/common/common.js
  src/css/common.css
  src/pages/other/announce/AnnounceDetail.js
  src/pages/other/announce/Announces.js
  src/pages/other/announce/InsertAnnounce.js
Labels: 🎈API, 💻Feature

#19 fix # 1- [캘린더] 일정등록 에러
  src/App.js
  src/apis/CalendarAPICalls.js
  src/components/Sidebar.js
  src/pages/calendar/Calendar.jsx
Labels: 🌀BugFix

#26 fix #1 - [로그인] 로그인 아이디 초과 에러
  package-lock.json
  src/App.js
  src/apis/MemberAPICalls.js
  src/components/Header.js
  src/components/Sidebar.js
  src/pages/member/Login.js
  src/pages/member/Login.module.css
  src/pages/member/ManageMember.js
  src/pages/member/ManageMember.module.css
  src/pages/member/RegisterMember.js
  src/pages/profile/HistoryInfo.js
  src/pages/profile/MyProfile.js
  src/pages/profile/MyProfile.module.css
  src/style.css
Labels: 🌀BugFix

#28 fix #7 - [공지사항] 공지사항 수정 기존 데이터 안보이던 버그
  src/pages/other/announce/UpdateAnnounce.js
Labels: 🌀BugFix

#29 feat #2 - [출퇴근] 멤버 출퇴근 조회 기능
  src/apis/CommonAPI.js
  src/apis/CommuteAPICalls.js
  src/components/commutes/CommuteItem.js
  src/components/commutes/CommuteListByMember.js
  src/components/commutes/CommuteTime.js
  src/css/commute/commute.css
  src/modules/CommuteModule.js
  src/pages/commute/RecordCommute.js
  src/pages/commute/RecordCorrectionOfCommute.js
Labels: 🎈API, 💻Feature

#30 feat #2 - [캘린더] 일정 조회
  src/apis/CalendarAPICalls.js
  src/modules/CalendarModule.js
  src/pages/calendar/Calendar.jsx
Labels: 🎈API, 💻Feature

#34 feat #4 - [캘린더] 일정 상세 조회
  src/pages/calendar/Calendar.jsx
  src/pages/calendar/Modal.js
  src/pages/calendar/UpdateModal.js
Labels: 💻Feature

#36 feat #5 - [캘린더] 일정 삭제
  src/apis/CalendarAPICalls.js
  src/modules/CalendarModule.js
  src/pages/calendar/Calendar.jsx
  src/pages/calendar/UpdateModal.js
Labels: 🎈API, 💻Feature

#38 Feat#1 [쪽지] - 쪽지 전체조회 (보낸 쪽지 / 받은 쪽지)
  src/App.js
  src/apis/NoteAPICalls.js
  src/components/Header.js
  src/components/Sidebar.js
  src/css/announce/ancDetail.css
  src/css/common.css
  src/css/note/noteLists.css
  src/modules/NoteMudule.js
  src/modules/index.js
  src/pages/announce/AnnounceDetail.js
  src/pages/announce/Announces.js
  src/pages/announce/InsertAnnounce.js
  src/pages/announce/UpdateAnnounce.js
  src/pages/insite/Insite.js
  src/pages/note/ReceiveNoteList.js
  src/pages/note/SendNoteList.js
Labels: 🎈API, 🌀BugFix, 💻Feature

#40 Feat#2 [쪽지] - 쪽지 삭제 ( 수정 )
  src/apis/NoteAPICalls.js
  src/components/Sidebar.js
  src/modules/NoteMudule.js
  src/pages/announce/Announces.js
  src/pages/note/ReceiveNoteList.js
  src/pages/note/SendNoteList.js
Labels: 🎈API, 💻Feature

#43 feat #2 - [출퇴근] 멤버별 출퇴근 내역 조회 시, 실제 근로 시간, 잔여 근로 시간 조회 기능 추가
  src/apis/CommonAPI.js
  src/apis/CommuteAPICalls.js
  src/components/commutes/CommuteItem.js
  src/components/commutes/CommuteListByMember.js
  src/components/commutes/CommuteTime.js
  src/pages/commute/RecordCommute.js
  src/pages/commute/RecordCorrectionOfCommute.js
Labels: 🎈API, 🌀BugFix, 💻Feature

#45 fix #4 - [출퇴근] 출퇴근 조회 시 시간 차이로 인해 렌더링 날짜 오류
  src/components/commutes/CommuteItem.js
  src/components/commutes/CommuteTime.js
  src/pages/commute/RecordCommute.js
Labels: 🎈API, 🌀BugFix

#51 feat #5 - [출퇴근] 출근 시간 등록
  src/apis/CommonAPI.js
  src/apis/CommuteAPICalls.js
  src/components/commutes/CommuteTime.js
  src/modules/CommuteModule.js
  src/pages/commute/RecordCommute.js
Labels: 🎈API, 💻Feature

#53 fix #6 - [출퇴근] 출근 시간 등록 시, 날짜 오류
  src/components/commutes/CommuteTime.js
  src/pages/commute/RecordCommute.js
Labels: 🎈API, 🌀BugFix

#55 feat #1- [휴가] 나의 휴가 내역 조회
  src/App.js
  src/apis/LeaveAPICalls.js
  src/apis/NoteAPICalls.js
  src/components/Sidebar.js
  src/modules/LeaveModule.js
  src/modules/index.js
  src/pages/leave/MyLeave.css
  src/pages/leave/MyLeave.js
  src/pages/leave/utill/leaveUtill.js
Labels: 🎈API, 💻Feature

#56 fix #8 - [출퇴근] 출퇴근 조회 시, 출퇴근 데이터가 없는 지나간 날짜의 정정 요청 버튼 렌더링 되지 않는 문제
  src/components/commutes/CommuteItem.js
  src/components/commutes/CommuteListByMember.js
Labels: 🌀BugFix

#58 feat #2 - [휴가] 나의 휴가 내역 조회 리팩토링
  src/pages/leave/MyLeave.js
  src/pages/leave/utill/leaveUtill.js
Labels: 💻Feature, 🥝Refactor

#60 fix #3 - [휴가] 나의 휴가 내역 조회 로딩 기능 수정
  src/apis/LeaveAPICalls.js
  src/css/common.css
  src/pages/leave/MyLeave.js
  src/pages/leave/utill/leaveUtill.js
Labels: 🌀BugFix

#62 fix #4 - [휴가] 로딩 관련 이슈 수정
  src/pages/leave/MyLeave.css
  src/pages/leave/MyLeave.js
Labels: 🌀BugFix

#63 feat #2 [구성원 등록]
  src/components/Header.js
  src/pages/calendar/Calendar.jsx
Labels: 🌀BugFix, 💻Feature

#65 Feat#3 [쪽지] - 쪽지 발송 / 멤버 전체 리스트 조회 API
  package-lock.json
  package.json
  src/apis/ChattingAPICalls.js
  src/apis/NoteAPICalls.js
  src/components/Header.js
  src/css/note/sendNoteForm.css
  src/modules/NoteMudule.js
  src/pages/note/ReceiveNoteList.js
  src/pages/note/SendNoteForm.js
  src/pages/note/SendNoteList.js
Labels: 🎈API, 💻Feature

#68 feat #2 - [캘린더] 모달창 형태 수정
  package-lock.json
  package.json
  src/pages/calendar/Calendar.jsx
  src/pages/calendar/CalendarModal.css
  src/pages/calendar/CalendarModal.js
  src/pages/calendar/CalendarUpdateModal.js
Labels: 🌀BugFix

#69 Feat#1전자결재상신함조회
  .vscode/launch.json
  src/App.js
  src/apis/ApprovalAPICalls.js
  src/components/Sidebar.js
  src/css/approval/approval.css
  src/modules/ApprovalModule.js
  src/pages/approval/SendApprovalList.js
Labels: 🎈API, 💻Feature

#70 Feat#1전자결재상신함조회
  .vscode/launch.json
  src/App.js
  src/apis/ApprovalAPICalls.js
  src/components/Sidebar.js
  src/css/approval/approval.css
  src/modules/ApprovalModule.js
  src/pages/approval/SendApprovalList.js
Labels: 🎈API, 💻Feature

#72 fix #9 - 화면 렌더링 오류
  src/apis/CommonAPI.js
  src/apis/CommuteAPICalls.js
  src/components/commutes/CommuteListByMember.js
  src/modules/CommuteModule.js
  src/pages/commute/RecordCommute.js
Labels: 🎈API, 🌀BugFix

#71 Feat#1전자결재상신함조회
  src/apis/ApprovalAPICalls.js
  src/modules/ApprovalModule.js
  src/pages/approval/SendApprovalList.js
Labels: 🎈API, 💻Feature

#74 fix #3 - [캘린더] 일정 등록 및 수정 시 시차 발생
  src/pages/calendar/Calendar.jsx
  src/pages/calendar/CalendarModal.js
  src/pages/calendar/CalendarUpdateModal.js
  src/pages/leave/MyLeave.js
  src/utils/CalendarUtill.js
  src/utils/leaveUtill.js
Labels: 🌀BugFix

#76 Feat#1전자결재상신함조회
  src/App.js
  src/components/Sidebar.js
  src/css/approval/approval.css
  src/pages/approval/SendApprovalList.js
Labels: 🎈API, 💻Feature

#78 feat #1 - [채팅] 채팅 화면 및 채팅방 목록 조회
  package-lock.json
  package.json
  src/App.js
  src/apis/AncAPICalls.js
  src/apis/ChattingAPICalls.js
  src/components/Header.js
  src/css/chat.css
  src/css/chatting/insertRoom.css
  src/css/chatting/roomList.css
  src/modules/AnnounceModule.js
  src/modules/CahttingModules.js
  src/pages/announce/AnnounceDetail.js
  src/pages/announce/InsertAnnounce.js
  src/pages/announce/UpdateAnnounce.js
  src/pages/chatting/InsertRoomModal.js
  src/pages/chatting/Room.js
  src/pages/chatting/RoomList.js
  src/utils/tokenUtils.js
Labels: 🎈API, 💻Feature

#80 feat#1 전자결재 상신함 조회
  src/apis/ApprovalAPICalls.js
  src/components/approvals/AppList.js
  src/modules/ApprovalModule.js
  src/pages/approval/SendApprovalList.js
  src/utils/tokenUtils.js
Labels: 🎈API, 💻Feature

#84 feat #1 - [메인] 주간 캘린더 추가
  src/pages/Main.css
  src/pages/Main.js
Labels: 🎈API, 💻Feature

#85 feat #7 - [출퇴근] 퇴근 시간 등록 (update)
  src/apis/CommonAPI.js
  src/apis/CommuteAPICalls.js
  src/modules/CommuteModule.js
  src/pages/commute/RecordCommute.js
  src/utils/tokenUtils.js
Labels: 🎈API, 🌀BugFix, 💻Feature

#91 feat#2 - [채팅] 실시간 채팅 서버 연결 완료
  package-lock.json
  package.json
  src/apis/ChattingAPICalls.js
  src/css/chatting/room.css
  src/css/chatting/roomList.css
  src/modules/CahttingModules.js
  src/modules/index.js
  src/pages/chatting/Room.js
  src/pages/chatting/RoomList.js
  src/pages/note/ReceiveNoteList.js
  src/pages/note/SendNoteList.js
Labels: 🎈API, 🌀BugFix, 💻Feature

#88 feat#1 전자결재 상신함 조회
  src/App.js
  src/apis/ApprovalAPI.js
  src/apis/ApprovalAPICalls.js
  src/components/Sidebar.js
  src/components/approvals/ApprovalListComponent.js
  src/modules/ApprovalModule.js
  src/pages/approval/ApprovalList.js
  src/pages/approval/SendApprovalList.js
Labels: 🎈API, 💻Feature

#93 feat #3 - [휴가] 휴가 등록
  src/pages/Main.js
  src/pages/leave/LeaveInsertModal.js
  src/utils/CommonUtil.js
  src/utils/leaveUtil.js
Labels: 🎈API, 💻Feature

#95 feat #8 - [캘린더] CalendarUtil.js 에 있던 convertToUtc 함수 CommonUtil.js로 이동
  src/pages/calendar/Calendar.jsx
  src/pages/leave/MyLeave.js
  src/utils/CalendarUtil.js
Labels: 🥝Refactor

#96 fix #9 - [출퇴근] 출퇴근 등록 시, 같은 날짜에 여러번 출퇴근 등록되는 이슈
  package-lock.json
  src/apis/CommuteAPICalls.js
  src/css/commute/commute.css
  src/pages/commute/ClockInModal.js
  src/pages/commute/RecordCommute.js
Labels: 🌀BugFix, 💻Feature

#97 fix #1 - [사이드바] 사이드 바 / 헤더 토글 오류 수정
  src/common/common.js
  src/components/Sidebar.js
  src/pages/Main.js
  src/pages/announce/AnnouceList.js
  src/pages/announce/Announces.js
Labels: 🌀BugFix, 🥝Refactor

#98 feat #5 - [휴가] 휴가 신청 삭제
  src/apis/LeaveAPICalls.js
  src/pages/calendar/Calendar.jsx
  src/pages/calendar/CalendarModal.js
  src/pages/leave/MyLeave.js
  src/utils/leaveUtil.js
Labels: 🎈API, 💻Feature

#101 style #1 - [메인/쪽지/공지사항] css 수정
  src/css/note/noteLists.css
  src/pages/Main.js
  src/pages/announce/AnnouceList.js
  src/pages/note/ReceiveNoteList.js
  src/pages/note/SendNoteList.js
Labels: ✨Style

#104 view
  src/App.js
  src/apis/DepartmentAPICalls.js
  src/apis/MemberAPICalls.js
  src/apis/PositionAPICalls.js
  src/components/Sidebar.js
  src/css/leave/MyLeave.css
  src/modules/DepartmentAndPositionModule.js
  src/pages/department&position/departmentAndPosition.js
  src/pages/department&position/departmentAndPosition.module.css
  src/pages/member/ManageMember.js
  src/pages/member/ManageMember.module.css
  src/pages/member/RegistMember.module.css
  src/pages/member/RegisterMember.js
Labels: 💻Feature

#106 feat #5 - [휴가] 휴가 취소 신청
  src/css/leave/LeaveModal.css
  src/css/leave/MyLeave.css
  src/css/leave/MyLeaveModal.css
  src/pages/leave/LeaveInsertModal.js
  src/pages/leave/MyLeave.js
  src/pages/leave/MyLeaveModal.js
  src/utils/leaveUtil.js
Labels: 🎈API, 💻Feature

#107 Feat#1전자결재상신함조회
  src/App.js
  src/apis/ApprovalAPI.js
  src/components/Sidebar.js
  src/components/approvals/ApprovalListComponent.js
  src/components/approvals/Pagination.js
  src/css/approval/ApprovalListComponent.module.css
  src/css/approval/approval.css
  src/pages/approval/ApprovalList.js
  src/pages/approval/SendApprovalList.js
Labels: 🎈API, 💻Feature

#110 feat#3 - [채팅] 방 생성 완료
  package-lock.json
  package.json
  src/apis/ChattingAPICalls.js
  src/css/chatting/customButton.css
  src/css/chatting/joinRoom.css
  src/css/chatting/room.css
  src/modules/CahttingModules.js
  src/modules/index.js
  src/pages/chatting/CustomButton.js
  src/pages/chatting/JoinRoom.js
  src/pages/chatting/Room.js
  src/pages/chatting/RoomList.js
  src/pages/openAPI/OpenAPI.js
Labels: 🎈API, 💻Feature

#111 feat #11 - [출퇴근] 출퇴근 정정 요청 등록
  package-lock.json
  package.json
  src/apis/CommuteAPICalls.js
  src/components/commutes/ClockInModal.js
  src/components/commutes/CommuteItem.js
  src/components/commutes/CommuteListByMember.js
  src/components/commutes/InsertCorrectionModal.js
  src/css/commute/commute.css
  src/modules/CommuteModule.js
  src/pages/commute/CommuteManage.js
  src/pages/commute/RecordCommute.js
Labels: 🎈API, 💻Feature

#117 Feat#5 [쪽지] - 쪽지 리스트 회원 별로 프사 + 이름 + 사번 보이도록 수정
  src/pages/note/ReceiveNoteList.js
  src/pages/note/SendNoteList.js
Labels: 🌀BugFix, 🥝Refactor, ✨Style

#119 Feat#1전자결재상신함조회
  src/components/approvals/ApprovalListComponent.js
  src/components/approvals/DeleteConfirmModal.js
  src/components/approvals/Pagination.js
  src/css/approval/ApprovalListComponent.module.css
  src/css/approval/DeleteConfirmModal.module.css
  src/css/approval/approval.css
  src/css/chatting/customButton.css
  src/modules/ApprovalReducer.js
  src/pages/approval/ApprovalList.js
Labels: 🎈API, 💻Feature, 🥝Refactor

#121 feat #6 - [휴가] 휴가 발생 관리
  src/App.js
  src/apis/LeaveAPICalls.js
  src/css/calendar/CalendarModal.css
  src/css/leave/LeaveAccrual.css
  src/css/leave/LeaveAccrualModal.css
  src/css/leave/MyLeave.css
  src/css/leave/MyLeaveModal.css
  src/modules/LeaveModule.js
  src/pages/calendar/CalendarModal.js
  src/pages/calendar/CalendarUpdateModal.js
  src/pages/leave/LeaveAccrual.js
  src/pages/leave/LeaveAccrualModal.js
  src/pages/leave/MyLeave.js
  src/pages/leave/MyLeaveModal.js
  src/utils/leaveUtil.js
Labels: 🎈API, 💻Feature

#122 Feat#1전자결재상신함조회 및 삭제
  src/App.js
  src/apis/ApprovalAPI.js
  src/apis/ApprovalAPICalls.js
  src/components/approvals/AppList.js
  src/components/approvals/ApprovalListComponent.js
  src/components/approvals/DeleteConfirmModal.js
  src/components/approvals/Pagination.js
  src/css/approval/ApprovalListComponent.module.css
  src/css/approval/DeleteConfirmModal.module.css
  src/modules/ApprovalModule.js
  src/modules/ApprovalReducer.js
  src/modules/index.js
  src/pages/approval/ApprovalList.js
  src/pages/approval/SendApprovalList.js
Labels: 🎈API, 💻Feature

#125 feat#2 전자결재 수신함 조회
  src/components/Sidebar.js
  src/components/approvals/ApprovalListComponent.js
  src/css/approval/ApprovalListComponent.module.css
  src/pages/approval/ApprovalList.js
Labels: 🎈API, 💻Feature

#134 feat #12 - [출퇴근] 멤버별 출퇴근 정정 내역 조회
  package-lock.json
  public/favicon.ico
  public/index.html
  src/apis/CommonAPI.js
  src/apis/CommuteAPICalls.js
  src/components/commutes/CommuteListByMember.js
  src/components/commutes/CommuteTime.js
  src/components/commutes/CorrectionItem.js
  src/components/commutes/InsertCorrectionModal.js
  src/modules/CommuteModule.js
  src/pages/commute/CommuteManage.js
  src/pages/commute/RecordCommute.js
  src/pages/commute/RecordCorrectionOfCommute.js
Labels: 🎈API, 💻Feature

#133 Feat#3전자결재기안
  src/App.js
  src/apis/ApprovalAPI.js
  src/components/Sidebar.js
  src/components/approvals/ApprovalListComponent.js
  src/components/approvals/SelectFormComponent.js
  src/css/approval/insertApproval.css
  src/modules/ApprovalReducer.js
  src/pages/approval/ApprovalInsert.js
  src/pages/approval/ApprovalPage.js
Labels: 🎈API, 💻Feature

#136 feat #5 - [채팅] 방 삭제
  src/App.js
  src/apis/ChattingAPICalls.js
  src/css/chatting/customButton.css
  src/css/chatting/customDropdown.css
  src/css/chatting/roomList.css
  src/modules/CahttingModules.js
  src/pages/chatting/JoinRoom.js
  src/pages/chatting/RoomList.js
  src/pages/member/Login.js
  src/pages/note/ReceiveNoteList.js
  src/pages/note/SendNoteList.js
Labels: 🎈API, 💻Feature

#137 부서, 직급 CRUD 기능 구현
  package-lock.json
  package.json
  src/App.js
  src/apis/DepartmentAPICalls.js
  src/apis/PositionAPICalls.js
  src/components/Header.js
  src/css/department/department.css
  src/pages/department&position/DepartDeleteModal.js
  src/pages/department&position/DepartNameModal.js
  src/pages/department&position/DepartRegistModal.js
  src/pages/department&position/PositionDeleteModal.js
  src/pages/department&position/PositionNameModal.js
  src/pages/department&position/PositionRegisterModal.js
  src/pages/department&position/departmentAndPosition.js
  src/pages/department&position/departmentAndPosition.module.css
  src/pages/member/ManageMember.js
Labels: 🌀BugFix, 💻Feature

#139 feat #7 - [휴가] Module, APICalls 리팩토링
  src/apis/LeaveAPICalls.js
  src/modules/LeaveModule.js
  src/pages/leave/LeaveAccrual.js
  src/pages/leave/MyLeave.js
Labels: 🥝Refactor

#141 구성원 사진 경로 설정
  public/img/240503184_구성원사진_샘플1.jpeg
  public/img/240518571_고윤정 증명사진.jpeg
Labels: 🌀BugFix, 💻Feature

#148 구성원 상세 조회, 비밀번호 변경 기능 구현
  package-lock.json
  public/img/240502675_고윤정 증명사진.jpeg
  src/apis/MemberAPICalls.js
  src/components/Header.js
  src/css/member/profile.css
  src/modules/PasswordReducer.js
  src/pages/member/RegisterMember.js
  src/pages/profile/ChangePasswordModal.js
  src/pages/profile/MyProfile.js
Labels: 💻Feature

#149 Feat#3전자결재기안
  package-lock.json
  package.json
  src/components/approvals/TinyEditor.js
  src/css/approval/insertApproval.css
  src/pages/approval/ApprovalInsert.js
Labels: 🎈API, 💻Feature

#151 feat #9 - [휴가] 휴가 보유 내역 조회
  src/App.js
  src/apis/LeaveAPICalls.js
  src/components/Sidebar.js
  src/pages/leave/Leaves.js
  src/utils/leaveUtil.js
Labels: 🎈API, 💻Feature

#153 fix #14 - [출퇴근] 출퇴근 정정 내역 조회/상세 조회 시 기존 출퇴근 데이터 값 렌더링 추가
  package.json
  src/apis/CommonAPI.js
  src/apis/CommuteAPICalls.js
  src/components/commutes/CommuteItem.js
  src/components/commutes/CorrectionDetailModal.js
  src/components/commutes/CorrectionItem.js
  src/components/commutes/CorrectionManageItem.js
  src/components/commutes/CorrectionUpdateModal.js
  src/components/commutes/InsertCorrectionModal.js
  src/modules/CommuteModule.js
  src/pages/commute/CommuteCorrectionManage.js
  src/pages/commute/RecordCommute.js
  src/pages/commute/RecordCorrectionOfCommute.js
Labels: 🎈API, 🌀BugFix, 💻Feature

#154 feat#3 전자결재 기안
  src/components/approvals/TinyEditor.js
  src/pages/approval/ApprovalInsert.js
Labels: 🎈API, 💻Feature

#158 feat #1 - [통계] 부서별 구성원 숫자 인사이트
  public/img/240501847_jjang.png
  public/img/240502382_hooni.jpg
  public/img/gpt.jpg
  src/apis/InsiteAPICalls.js
  src/components/Header.js
  src/css/chatting/room.css
  src/modules/InsiteModule.js
  src/modules/index.js
  src/pages/chatting/JoinRoom.js
  src/pages/chatting/Room.js
  src/pages/chatting/RoomList.js
  src/pages/insite/Insite.js
  src/pages/note/ReceiveNoteList.js
  src/pages/note/SendNoteList.js
Labels: 🎈API, 💻Feature

#161 feat #13 - [출퇴근] 멤버별 출퇴근 정정 내역 상세 조회
  src/apis/CommuteAPICalls.js
  src/components/commutes/CorrectionItem.js
  src/components/commutes/CorrectionManageItem.js
  src/components/commutes/CorrectionUpdateModal.js
  src/css/commute/commute.css
  src/modules/CommuteModule.js
  src/pages/commute/CommuteCorrectionManage.js
  src/pages/commute/RecordCommute.js
  src/pages/commute/RecordCorrectionOfCommute.js
Labels: 🎈API, 🌀BugFix, 💻Feature

#162 feat #3 전자결재 기안
  src/components/approvals/SelectFormComponent.js
  src/components/approvals/TinyEditor.js
  src/pages/approval/ApprovalInsert.js
Labels: 🎈API, 💻Feature

#167 feat #1 - [통계] 금일 휴가자 / 금일 출근자 현황 통계
  src/apis/InsiteAPICalls.js
  src/apis/NoteAPICalls.js
  src/modules/InsiteModule.js
  src/pages/announce/AnnouceList.js
  src/pages/announce/InsertAnnounce.js
  src/pages/insite/DepartInsite.js
  src/pages/insite/Insite.js
  src/pages/insite/LeaveInsite.js
  src/pages/note/ReceiveNoteList.js
  src/pages/note/SendNoteList.js
Labels: 🎈API, 💻Feature

#168 Feat#3전자결재기안
  src/apis/ApprovalAPI.js
  src/components/approvals/TinyEditor.js
  src/components/approvals/UserInfoComponent.js
  src/pages/approval/ApprovalInsert.js
Labels: 🎈API, 💻Feature

#170 style #8 - [채팅] 채팅 방 생성 화면 꾸미기
  src/css/chatting/customButton.css
  src/css/chatting/joinRoom.css
  src/css/chatting/roomList.css
  src/pages/chatting/JoinRoom.js
  src/pages/chatting/RoomList.js
  src/pages/insite/DepartInsite.js
  src/pages/insite/LeaveInsite.js
Labels: 🥝Refactor, ✨Style

#173 feat #2 - [수요조사] 수요조사 제목 관련 리팩토링 및 css 수정
  src/css/survey/SurveyModal.css
  src/css/survey/surveyList.css
  src/pages/survey/SurveyModal.js
  src/utils/SurveyUtil.js
Labels: 🥝Refactor

#175 feat #3 - [수요조사] 수요조사 등록
  src/apis/SurveyAPICalls.js
  src/css/survey/SurveyInsertModal.css
  src/modules/SurveyModule.js
  src/pages/survey/SurveyInsertModal.js
  src/pages/survey/SurveyList.js
Labels: 🎈API, 💻Feature

#177 feat #2 - [메인] 임시 로그아웃 버튼 삭제
  src/pages/Main.js
Labels: 🥝Refactor

#179 feat #10 - [휴가] 휴가 보유 내역 css 수정
  src/css/leave/Leaves.css
  src/pages/leave/Leaves.js
  src/utils/leaveUtil.js
Labels: 🥝Refactor

#182 구성원 상세 조회 및 정보 수정, 근속년수 버그 수정
  public/img/123_증명사진232.jpeg
  public/img/240401552_김민재 증명사진.jpeg
  public/img/240502671_증명사진123.jpeg
  public/img/240503700_empty_file
  public/img/240503700_profiel_pic_jeehwan.JPG
  public/img/240503700_고윤정 증명사진.jpeg
  public/img/240503700_구성원사진_샘플1.jpeg
  public/img/240503700_유병재 사진.jpeg
  public/img/240503700_증명사진123.jpeg
  public/img/240503700_증명사진232.jpeg
  public/img/240505191_증명사진123.jpeg
  public/img/24051785_유병재 사진.jpeg
  public/img/24051785_증명사진232.jpeg
  public/img/240520839_empty_file
  public/img/240520839_구성원사진_샘플1.jpeg
  public/img/240520839_증명사진232.jpeg
  public/img/24052648_증명사진232.jpeg
  public/img/24055295_구성원사진_샘플1.jpeg
  public/img/241811_유병재 사진.jpeg
  src/apis/DepartmentAPICalls.js
  src/apis/MemberAPICalls.js
  src/css/member/login.css
  src/css/member/memberPage.css
  src/css/member/registerMember.css
  src/css/member/setMember.css
  src/pages/member/Login.js
  src/pages/member/Login.module.css
  src/pages/member/ManageMember.js
  src/pages/member/ManageMember.module.css
  src/pages/member/MemberPage.js
  src/pages/member/RegisterMember.js
  src/pages/profile/ChangePasswordModal.js
  src/pages/profile/MyProfile.js
Labels: 🌀BugFix, 💻Feature

#183 Feat#3전자결재기안
  src/apis/ApprovalAPI.js
  src/components/approvals/ApproverModal.js
  src/components/approvals/CancelModal.js
  src/components/approvals/UserInfoComponent.js
  src/css/approval/ApprovalListComponent.module.css
  src/css/approval/UserInfoComponent.module.css
  src/css/approval/approverModal.css
  src/css/approval/cancelModal.css
  src/modules/ApprovalReducer.js
  src/pages/approval/ApprovalInsert.js
Labels: 🎈API, 💻Feature

#186 feat #11, fix #3 - [휴가] useEffect 구문 및 조회 로직 리팩토링 , 페이징 문제 해결
  src/apis/LeaveAPICalls.js
  src/pages/leave/LeaveAccrual.js
  src/pages/leave/LeaveAccrualModal.js
  src/pages/leave/LeaveProcessing.js
  src/pages/leave/Leaves.js
  src/pages/leave/MyLeave.js
Labels: 🌀BugFix, 🥝Refactor

#184 feat#4 전자결재 결재선 참조선 연결 및 조회
  src/components/approvals/ApproverModal.js
  src/components/approvals/CancelModal.js
  src/components/approvals/UserInfoComponent.js
  src/css/approval/UserInfoComponent.module.css
  src/css/approval/approverModal.css
  src/css/approval/cancelModal.css
  src/css/approval/insertApproval.css
  src/pages/approval/ApprovalInsert.js
Labels: 🎈API, 💻Feature

#188 feat #12 - [휴가] 나의 휴가 관리 처리 상태 현출 로직 리팩토링
  src/pages/leave/LeaveProcessing.js
  src/pages/leave/MyLeave.js
  src/utils/leaveUtil.js
Labels: 🥝Refactor

#190 feat #13 - [휴가] 가독성 향상을 위한 리팩토링
  src/pages/leave/LeaveAccrual.js
  src/pages/leave/LeaveAccrualModal.js
  src/pages/leave/LeaveProcessing.js
  src/pages/leave/LeaveProcessingModal.js
  src/pages/leave/Leaves.js
  src/pages/leave/MyLeave.js
  src/pages/leave/MyLeaveModal.js
Labels: 🥝Refactor

#191 Fix#1전자결재기안 css 수정
  src/components/approvals/ApproverModal.js
  src/components/approvals/SelectFormComponent.js
  src/components/approvals/TinyEditor.js
  src/components/approvals/UserInfoComponent.js
  src/css/approval/ApprovalInsert.module.css
  src/css/approval/ApprovalListComponent.module.css
  src/css/approval/ApproverModal.module.css
  src/css/approval/SelectFormComponent.module.css
  src/css/approval/UserInfoComponent.module.css
  src/pages/approval/ApprovalInsert.js
Labels: 🌀BugFix, ✨Style

#192 feat#4 전자결재 기안 화면 구현 및 수정
  src/apis/ApprovalAPI.js
  src/components/approvals/ApproverModal.js
  src/components/approvals/TinyEditor.js
  src/components/approvals/UserInfoComponent.js
  src/css/approval/ApprovalInsert.module.css
  src/css/approval/ApproverModal.module.css
  src/css/approval/UserInfoComponent.module.css
  src/modules/ApprovalReducer.js
  src/pages/approval/ApprovalInsert.js
Labels: 🎈API, 💻Feature

#196 feat #3 - [메인] 메인 카드 4개 추가
  .gitignore
  public/index.html
  src/apis/InsiteAPICalls.js
  src/common/ApprovalCounts.js
  src/common/ApproverCounts.js
  src/common/ClockContainer.js
  src/common/MyLeaveCounts.js
  src/common/Weather.js
  src/css/ApprovalCounts.css
  src/css/ApproverCounts.css
  src/css/ClockContainer.css
  src/css/MyLeaveCounts.css
  src/css/main.css
  src/css/weather.css
  src/modules/ApprovalReducer.js
  src/modules/InsiteModule.js
  src/pages/Main.js
  src/pages/note/SendNoteForm.js
Labels: 🎈API, 💻Feature

#198 feat #15 - [휴가] 휴가 신청 유효성 검사 추가
  src/css/leave/MyLeaveModal.css
  src/pages/leave/MyLeave.js
  src/pages/leave/MyLeaveModal.js
  src/utils/leaveUtil.js
Labels: 💻Feature

#204 feat #9 - [캘린더] 일정 등록 시 유효성 검사 추가
  src/css/leave/MyLeaveModal.css
  src/pages/calendar/Calendar.js
  src/pages/calendar/CalendarModal.js
  src/pages/leave/MyLeaveModal.js
  src/pages/survey/SurveyInsertModal.js
Labels: 💻Feature

#206 구성원 성별, 생일 정보 추가
  public/img/240501467_profiel_pic_jeehwan.JPG
  public/img/240502512_모태미남증명사진.jpeg
  public/img/240503895_모태미남증명사진.jpeg
  public/img/240518238_모태미남증명사진.jpeg
  public/img/24052375_모태미남증명사진.jpeg
  public/img/24055819_모태미남증명사진.jpeg
  src/App.js
  src/css/department/departmentNameModal.css
  src/css/member/hierarchyTree.css
  src/css/member/memberPage.css
  src/css/member/profile.css
  src/css/member/registerMember.css
  src/css/member/setMember.css
  src/pages/department&position/PositionRegisterModal.js
  src/pages/departmentAndposition/DepartDeleteModal.js
  src/pages/departmentAndposition/DepartNameModal.js
  src/pages/departmentAndposition/DepartRegistModal.js
  src/pages/departmentAndposition/PositionDeleteModal.js
  src/pages/departmentAndposition/PositionNameModal.js
  src/pages/departmentAndposition/PositionRegisterModal.js
  src/pages/departmentAndposition/departmentAndPosition.js
  src/pages/departmentAndposition/departmentAndPosition.module.css
  src/pages/member/HierarchyTree.js
  src/pages/member/MemberPage.js
  src/pages/member/RegisterMember.js
  src/pages/profile/MyProfile.js
Labels: 🌀BugFix

#208 feat #10 - [캘린더] 부서 선택 셀렉트박스 추가
  src/apis/CalendarAPICalls.js
  src/css/calendar/Calendar.css
  src/pages/calendar/Calendar.js
  src/pages/calendar/CalendarModal.js
  src/pages/calendar/CalendarUpdateModal.js
  src/pages/leave/Leaves.js
  src/utils/CalendarUtil.js
  src/utils/leaveUtil.js
Labels: 💻Feature

#211 직급 인원수 컬럼 추기, 부서 및 직급명을 누르면 해당 구성원의 정보 출력
  src/pages/departmentAndposition/DepartPeopleModal.js
  src/pages/departmentAndposition/DepartRegistModal.js
  src/pages/departmentAndposition/PositionPeopleModal.js
  src/pages/departmentAndposition/PositionRegisterModal.js
  src/pages/departmentAndposition/departmentAndPosition.js
Labels: 🌀BugFix, 💻Feature

#213 feat #17 - [출퇴근] 부서별 출퇴근 내역 조회
  src/apis/CommuteAPICalls.js
  src/components/commutes/CommuteCalendar.js
  src/components/commutes/CommuteDay.js
  src/components/commutes/CommuteItem.js
  src/components/commutes/CommuteListByMember.js
  src/components/commutes/CommuteMonth.js
  src/components/commutes/CommuteRow.js
  src/components/commutes/InsertCorrectionModal.js
  src/modules/CommuteModule.js
  src/pages/commute/CommuteManage.js
  src/pages/commute/RecordCommute.js
  src/pages/commute/RecordCorrectionOfCommute.js
  src/utils/CommuteUtil.js
Labels: 🎈API, 💻Feature

#214 Feat#3전자결재기안
  src/apis/ApprovalAPI.js
  src/components/approvals/CancelModal.js
  src/components/approvals/InsertConfirmModal.js
  src/components/approvals/InsertFailModal.js
  src/components/approvals/InsertSuccessModal.js
  src/components/approvals/TinyEditor.js
  src/components/approvals/WarningModal.js
  src/css/approval/ApprovalInsert.module.css
  src/css/approval/InsertConfirmModal.module.css
  src/css/approval/InsertFailModal.module.css
  src/css/approval/InsertSuccessModal.module.css
  src/css/approval/WarningModal.module.css
  src/pages/approval/ApprovalInsert.js
Labels: 🎈API, 💻Feature

#216 feat #11 - [캘린더] 부서 선택 셀렉트 박스에 전체 추가
  src/pages/calendar/Calendar.js
  src/utils/leaveUtil.js
Labels: 🥝Refactor

#217 feat #18 - [출퇴근] 부서별 출퇴근 내역 조회
  src/common/common.js
  src/components/Header.js
  src/components/commutes/CommuteCalendar.js
  src/components/commutes/CommuteDay.js
  src/components/commutes/CommuteMonth.js
  src/components/commutes/CommuteRow.js
  src/components/commutes/CorrectionManageItem.js
  src/css/commute/commute.css
  src/pages/Main.js
  src/pages/commute/CommuteCorrectionManage.js
  src/pages/commute/CommuteManage.js
  src/pages/commute/commute.css
Labels: 🎈API, 💻Feature, ✨Style

#221 feat #12 - [출퇴근] 멤버별 출퇴근 정정 내역 조회
  package-lock.json
  package.json
  src/apis/CommuteAPICalls.js
  src/common/common.js
  src/components/commutes/CorrectionDetailModal.js
  src/components/commutes/CorrectionItem.js
  src/pages/commute/RecordCorrectionOfCommute.js
Labels: 🎈API, 🌀BugFix, 🥝Refactor

#225 feat #4 - [통계] 전체적인 리팩토링
  src/apis/InsiteAPICalls.js
  src/modules/InsiteModule.js
  src/pages/Main.js
  src/pages/insite/Insite.js
Labels: 🎈API, 🌀BugFix, 💻Feature, 🥝Refactor

#227 fix #18 - [출퇴근] 출근시간/ 퇴근시간 등록 시 중복 입력되는 오류
  package-lock.json
  package.json
  src/components/commutes/ClockInModal.js
  src/components/commutes/ClockLimitModal.js
  src/components/commutes/ClockOutModal.js
  src/components/commutes/CommuteTime.js
  src/components/commutes/InsertCorrectionModal.js
  src/pages/commute/RecordCommute.js
Labels: 🌀BugFix, 🥝Refactor

#228 feat #19 - [출퇴근] 퇴근 시간 등록 시, 총 근무 시간 계산 로직 추가
  src/components/commutes/ClockOutModal.js
  src/components/commutes/CommuteListByMember.js
  src/components/commutes/InsertCorrectionModal.js
  src/pages/commute/RecordCommute.js
Labels: 💻Feature

#233 fix #3 - [휴가] 페이지 첫 렌더링 시 렌더링 반복
  src/pages/leave/LeaveAccrual.js
  src/pages/leave/LeaveProcessing.js
  src/pages/leave/Leaves.js
  src/pages/leave/MyLeave.js
Labels: 🌀BugFix

#235 fix #4 - [휴가] 휴가 페이징 오류 재수정
  src/pages/leave/LeaveAccrual.js
  src/pages/leave/LeaveProcessing.js
  src/pages/leave/Leaves.js
  src/pages/leave/MyLeave.js
Labels: 🌀BugFix

#236 feat #20 - [출퇴근] 전체 출퇴근 정정 내역 조회/ 상세 조회
  src/apis/CommuteAPICalls.js
  src/components/commutes/CommuteItem.js
  src/components/commutes/CommuteListByMember.js
  src/components/commutes/CorrectionManageItem.js
  src/components/commutes/CorrectionUpdateModal.js
  src/components/commutes/InsertCorrectionModal.js
  src/pages/commute/CommuteCorrectionManage.js
  src/pages/commute/CommuteManage.js
  src/pages/commute/RecordCorrectionOfCommute.js
Labels: 🎈API, 💻Feature

#238 feat #7 - [채팅] 채팅 메시지 저장 / 기존 메시지 불러오기
  src/apis/ChattingAPICalls.js
  src/components/Header.js
  src/css/announce/ancDetail.css
  src/modules/CahttingModules.js
  src/pages/Main.js
  src/pages/announce/AnnounceDetail.js
  src/pages/announce/Announces.js
  src/pages/announce/InsertAnnounce.js
  src/pages/announce/UpdateAnnounce.js
  src/pages/chatting/Room.js
  src/pages/chatting/RoomList.js
  src/pages/insite/Insite.js
  src/pages/note/ReceiveNoteList.js
  src/pages/note/SendNoteList.js
Labels: 🎈API, 🌀BugFix, 💻Feature, 🥝Refactor

#240 feat #16 - [휴가] 확인 모달 추가 및 리팩토링
  src/css/leave/LeaveAccrual.css
  src/css/leave/LeaveCheckModal.css
  src/css/leave/MyLeaveModal.css
  src/pages/leave/LeaveAccrualModal.js
  src/pages/leave/LeaveCheckModal.js
  src/pages/leave/LeaveProcessingModal.js
  src/pages/leave/MyLeave.js
  src/pages/leave/MyLeaveModal.js
  src/utils/leaveUtil.js
Labels: 💻Feature, 🥝Refactor

#219 feat#5 전자결재 임시저장
  package-lock.json
  package.json
  src/components/approvals/TempSaveModal.js
  src/css/approval/ApprovalInsert.module.css
  src/css/approval/TempSaveModal.module.css
  src/pages/approval/ApprovalInsert.js
Labels: 🎈API, 💻Feature

#245 fix #21 - [출퇴근] 출퇴근 등록, 정정 처리 시 내역 조회 API 재호출하는 기능 추가
  src/apis/CommuteAPICalls.js
  src/components/commutes/ClockInModal.js
  src/components/commutes/ClockOutModal.js
  src/components/commutes/CommuteItem.js
  src/components/commutes/CommuteListByMember.js
  src/components/commutes/CorrectionDetailModal.js
  src/components/commutes/CorrectionManageItem.js
  src/components/commutes/CorrectionUpdateModal.js
  src/components/commutes/InsertCorrectionModal.js
  src/pages/commute/CommuteCorrectionManage.js
  src/pages/commute/CommuteManage.js
  src/pages/commute/RecordCommute.js
  src/pages/commute/RecordCorrectionOfCommute.js
Labels: 🎈API, 🌀BugFix, ✨Style

#247 Feat#6 전자결재 재임시저장
  package-lock.json
  package.json
  src/modules/ApprovalReducer.js
  src/pages/approval/ApprovalInsert.js
Labels: 🎈API, 💻Feature

#248 feat#6 전자결재 재임시저장
  src/components/approvals/CancelInsertModal.js
  src/css/approval/CancelInsertModal.module.css
  src/pages/approval/ApprovalInsert.js
Labels: 🎈API, 💻Feature

#251 refactor #7 - 공지사항 파일 등록 갯수 제한
  src/pages/announce/InsertAnnounce.js
Labels: 🌀BugFix, 🥝Refactor

#253 feat #22 - [출퇴근] 부서별 전체 출퇴근 내역 조회에서 근무 시간 조회 기능 추가
  src/components/commutes/TotalWorkingHours.js
  src/pages/commute/CommuteManage.js
Labels: 💻Feature

#254 fix#1 전자결재 재임시저장 수정
  src/pages/approval/ApprovalInsert.js
Labels: 🥝Refactor

#255 feat#8 전자결재 상세조회 페이지 구현
  src/App.js
  src/apis/ApprovalAPI.js
  src/components/approvals/ApprovalListComponent.js
  src/components/approvals/ApproversInfo.js
  src/components/approvals/ReferencerComponent.js
  src/css/approval/ApprovalDetail.module.css
  src/css/approval/ApproversInfo.module.css
  src/css/approval/ReferencerComponent.module.css
  src/modules/ApprovalReducer.js
  src/pages/approval/ApprovalDetail.js
Labels: 🎈API, 💻Feature

#257 feat #8 - [채팅] 채팅방 삭제 -> delete : put 변경
  src/apis/ChattingAPICalls.js
  src/modules/CahttingModules.js
  src/pages/chatting/JoinRoom.js
  src/pages/chatting/Room.js
  src/pages/chatting/RoomList.js
Labels: 🎈API, 💻Feature, 🥝Refactor

#259 feat #12 - [캘린더] 일정 선택 시 유효성 검사 추가
  src/pages/calendar/CalendarModal.js
  src/pages/calendar/CalendarUpdateModal.js
Labels: 💻Feature

#261 feat #22 - [출퇴근] 기존 출퇴근 기록이 없을 때 출퇴근 정정 등록 기능 추가
  src/App.js
  src/apis/CommuteAPICalls.js
  src/apis/NoticeAPICalls.js
  src/components/Header.js
  src/components/commutes/ClockInModal.js
  src/components/commutes/ClockOutModal.js
  src/components/commutes/CommuteItem.js
  src/components/commutes/CommuteListByMember.js
  src/components/commutes/CommuteTime.js
  src/components/commutes/InsertCorrectionModal.js
  src/components/commutes/NewCommuteAndCorrection.js
  src/components/commutes/TotalWorkingHours.js
  src/modules/CommuteModule.js
  src/modules/NoticeModule.js
  src/modules/index.js
  src/pages/Main.js
  src/pages/commute/CommuteCorrectionManage.js
  src/pages/commute/CommuteManage.js
  src/pages/commute/RecordCommute.js
  src/utils/CommuteUtil.js
Labels: 🎈API, 💻Feature, ✨Style

#262 fix #1 - [메인] 렌더링 이슈 해결
  src/pages/Main.js
Labels: 🌀BugFix

#264 fix #9 - [채팅] 채팅방 생성: memberList 이미 존재하는 방일 시, memberList에서 제외
  src/pages/chatting/JoinRoom.js
  src/pages/chatting/Room.js
  src/pages/chatting/RoomList.js
Labels: 🌀BugFix, 🥝Refactor

#266 feat #17 - [휴가] 휴가 관련 리팩토링
  src/css/leave/LeaveAccrualModal.css
  src/css/leave/LeaveCheckModal.css
  src/css/leave/MyLeaveModal.css
  src/pages/leave/LeaveAccrualModal.js
  src/pages/leave/LeaveCheckModal.js
  src/pages/leave/LeaveProcessingModal.js
  src/pages/leave/MyLeave.js
  src/pages/leave/MyLeaveModal.js
Labels: 💻Feature, 🥝Refactor

#268 feat #23 - [출퇴근] 출퇴근 내역이 없을 때 출퇴근 정정 등록 시, 처리하는 로직
  src/components/commutes/CommuteItem.js
  src/components/commutes/CommuteListByMember.js
  src/components/commutes/NewCommuteAndCorrection.js
  src/pages/commute/CommuteCorrectionManage.js
  src/pages/commute/CommuteManage.js
  src/pages/commute/RecordCorrectionOfCommute.js
Labels: 🎈API, 💻Feature

#269 Feat#10전자결재 처리
  src/apis/ApprovalAPI.js
  src/components/approvals/ApproverStatusConfirmModal.js
  src/components/approvals/ReturnConfirmModal.js
  src/css/approval/ApprovalDetail.module.css
  src/css/approval/ApproverStatusConfirmModal.module.css
  src/css/approval/ReturnConfirmModal.module.css
  src/pages/approval/ApprovalDetail.js
Labels: 🎈API, 💻Feature

#270 05 28 jeez123
  package-lock.json
  package.json
  public/img/240528171_KakaoTalk_Photo_2024-05-28-15-06-44 001.jpeg
  public/img/240528292_KakaoTalk_Photo_2024-05-28-15-06-44 001.jpeg
  public/img/240528903_KakaoTalk_Photo_2024-05-28-15-06-44 002.jpeg
  src/css/department/departPeopleModal.css
  src/css/department/department.css
  src/css/department/departmentDelete.css
  src/css/department/departmentNameModal.css
  src/css/department/departmentRegistModal.css
  src/modules/ApprovalReducer.js
  src/pages/departmentAndposition/DepartDeleteModal.js
  src/pages/departmentAndposition/DepartNameModal.js
  src/pages/departmentAndposition/DepartPeopleModal.js
  src/pages/departmentAndposition/DepartRegistModal.js
  src/pages/departmentAndposition/PositionDeleteModal.js
  src/pages/departmentAndposition/PositionNameModal.js
  src/pages/departmentAndposition/PositionPeopleModal.js
  src/pages/departmentAndposition/PositionRegisterModal.js
  src/pages/member/HierarchyTree.js
  src/pages/member/Login.js
  src/pages/member/Login.module.css
  src/pages/member/Modal.js
  src/pages/member/ModalID.js
  src/pages/member/ModalPassword.js
  src/pages/member/RegisterMember.js
  src/pages/profile/ChangePasswordModal.js
Labels: 🌀BugFix

#272 feat #10 전자결재 처리
  src/components/approvals/TinyEditor.js
  src/css/approval/ApprovalDetail.module.css
  src/css/approval/TempSaveModal.module.css
  src/css/approval/WarningModal.module.css
  src/pages/approval/ApprovalDetail.js
Labels: 🎈API, 💻Feature

#281 feat #6 - [통계] 메인페이지 상신인 조건 추가
  src/apis/InsiteAPICalls.js
  src/common/ApprovalCounts.js
  src/common/ApproverCounts.js
  src/common/MyLeaveCounts.js
  src/pages/Main.js
  src/pages/chatting/Room.js
Labels: 🌀BugFix, 🥝Refactor

#283 feat 13 - [캘린더] 일정 등록, 수정 시 빨간색 삭제
  src/components/Sidebar.js
  src/css/leave/LeaveCheckModal.css
  src/css/leave/MyLeaveModal.css
  src/pages/calendar/Calendar.js
  src/pages/calendar/CalendarModal.js
  src/pages/calendar/CalendarUpdateModal.js
  src/pages/leave/LeaveAccrual.js
  src/pages/leave/LeaveCheckModal.js
  src/pages/leave/MyLeaveModal.js
  src/utils/CalendarUtil.js
  src/utils/leaveUtil.js
Labels: 🥝Refactor

#284 feat#10 전자결재 파일 다운로드
  src/apis/ApprovalAPI.js
  src/css/approval/ApprovalDetail.module.css
  src/pages/approval/ApprovalDetail.js
Labels: 🎈API, 💻Feature

#286 style #1 [버튼] 버튼 / hover 공통 색상으로 수정
  public/favicon.ico
  public/favicon.png
  public/img/logo.png
  public/index.html
  src/common/ApprovalCounts.js
  src/common/MyLeaveCounts.js
  src/css/announce/ancDetail.css
  src/css/announce/ancList.css
  src/css/chatting/deleteModal.css
  src/css/member/memberPage.css
  src/css/note/noteDetail.css
  src/pages/announce/AnnouceList.js
  src/pages/announce/Announces.js
  src/pages/announce/InsertAnnounce.js
  src/pages/note/NoteDetail.js
  src/pages/note/ReceiveNoteList.js
  src/pages/note/ResponseNoteModal.js
  src/pages/note/SendNoteList.js
Labels: ✨Style

#287 style #2 [버튼] 버튼 / hover 공통 색상으로 수정
  src/App.js
  src/apis/CommuteAPICalls.js
  src/apis/NoticeAPICalls.js
  src/components/Header.js
  src/components/commutes/AddWorkTimeModalBy8.js
  src/components/commutes/ClockInModal.js
  src/components/commutes/ClockLimitModal.js
  src/components/commutes/ClockOutModal.js
  src/components/commutes/ClockOutWarningModalBy52.js
  src/components/commutes/CommuteItem.js
  src/components/commutes/CorrectionDetailModal.js
  src/components/commutes/CorrectionUpdateModal.js
  src/components/commutes/InsertCorrectionModal.js
  src/components/commutes/NewCommuteAndCorrection.js
  src/css/commute/commute.css
  src/css/main.css
  src/css/member/manageMember.css
  src/css/member/profile.css
  src/css/member/setMember.css
  src/modules/CommuteModule.js
  src/pages/commute/CommuteCorrectionManage.js
  src/pages/commute/RecordCommute.js
  src/pages/commute/RecordCorrectionOfCommute.js
  src/pages/profile/HistoryInfo.js
  src/style.css
Labels: ✨Style

#290 style #2 [버튼] 버튼 / hover 공통 색상으로 수정
  src/components/commutes/ClockInModal.js
  src/css/chatting/room.css
  src/css/commute/commute.css
  src/css/note/noteDetail.css
  src/pages/Main.js
  src/pages/announce/AnnouceList.js
  src/pages/chatting/Room.js
Labels: ✨Style

#291 Fix#2전자결재 임시저장후기안 수정
  src/css/approval/ApprovalInsert.module.css
  src/css/approval/ApproverModal.module.css
  src/css/approval/CancelInsertModal.module.css
  src/css/approval/DeleteConfirmModal.module.css
  src/css/approval/InsertConfirmModal.module.css
  src/css/approval/InsertFailModal.module.css
  src/css/approval/InsertSuccessModal.module.css
  src/css/approval/ReturnConfirmModal.module.css
  src/css/approval/WarningModal.module.css
  src/css/approval/approval.css
  src/css/approval/cancelModal.css
  src/pages/approval/ApprovalInsert.js
Labels: 🎈API, 🌀BugFix, 💻Feature, 🥝Refactor

#293 feat #18 - [휴가] 휴가 발생 로직 변경
  src/components/Sidebar.js
  src/css/leave/LeaveAccrualModal.css
  src/css/leave/LeaveProcessing.css
  src/css/leave/MyLeave.css
  src/pages/calendar/Calendar.js
  src/pages/leave/LeaveAccrual.js
  src/pages/leave/LeaveAccrualModal.js
  src/pages/survey/SurveyList.js
  src/utils/leaveUtil.js
Labels: 💻Feature, 🥝Refactor

#294 feat #24 - [출퇴근] 사이드탭 권한별 조건부 렌더링 및 버튼 css 스타일 변경
  package-lock.json
  package.json
  src/App.js
  src/apis/CommonAPI.js
  src/common/common.js
  src/components/Header.js
  src/components/Sidebar.js
  src/components/commutes/ClockInModal.js
  src/components/commutes/ClockLimitModal.js
  src/components/commutes/ClockOutModal.js
  src/components/commutes/CommuteItem.js
  src/components/commutes/CorrectionDetailModal.js
  src/components/commutes/CorrectionUpdateModal.js
  src/components/commutes/InsertCorrectionModal.js
  src/components/commutes/NewCommuteAndCorrection.js
  src/css/commute/commute.css
Labels: 🌀BugFix, ✨Style

#295 fix #25 - [사이드바] 중복 오류 수정
  src/components/Sidebar.js
Labels: 🌀BugFix

#297 style #2 [버튼] - 공통 버튼 css 추가
  src/css/common.css
  src/pages/calendar/Calendar.js
  src/pages/calendar/CalendarModal.js
  src/pages/calendar/CalendarUpdateModal.js
  src/pages/leave/LeaveAccrualModal.js
  src/pages/leave/LeaveCheckModal.js
  src/pages/leave/LeaveProcessingModal.js
  src/pages/leave/Leaves.js
  src/pages/leave/MyLeaveModal.js
  src/pages/survey/SurveyInsertModal.js
  src/pages/survey/SurveyList.js
  src/pages/survey/SurveyModal.js
Labels: ✨Style

#299 버튼 수정 및 조직도 생성
  package-lock.json
  package.json
  public/img/123_김민재 증명사진.jpeg
  public/img/240401835_profiel_pic_jeehwan.JPG
  public/img/240501268_구성원사진_샘플1.jpeg
  public/img/240502864_모태미남증명사진.jpeg
  public/img/240528108_유병재 사진.jpeg
  src/App.js
  src/apis/MemberAPICalls.js
  src/apis/PositionAPICalls.js
  src/components/Header.js
  src/components/PrivateRoute.js
  src/css/department/departPeopleModal.css
  src/css/department/department.css
  src/css/department/departmentDelete.css
  src/css/department/departmentNameModal.css
  src/css/department/departmentRegistModal.css
  src/css/member/hierarchyTree.css
  src/css/member/loginModal.css
  src/css/member/manageMember.css
  src/css/member/memberPage.css
  src/css/member/profile.css
  src/css/member/registerMember.css
  src/pages/departmentAndposition/DepartDeleteModal.js
  src/pages/departmentAndposition/DepartNameModal.js
  src/pages/departmentAndposition/DepartPeopleModal.js
  src/pages/departmentAndposition/DepartRegistModal.js
  src/pages/departmentAndposition/PositionDeleteModal.js
  src/pages/departmentAndposition/PositionNameModal.js
  src/pages/departmentAndposition/PositionPeopleModal.js
  src/pages/departmentAndposition/PositionRegisterModal.js
  src/pages/departmentAndposition/departmentAndPosition.module.css
  src/pages/member/ChangeMemberPage.js
  src/pages/member/HierarchyTree.js
  src/pages/member/Login.js
  src/pages/member/ManageMember.js
  src/pages/member/ManageMember.module.css
  src/pages/member/MemberPage.js
  src/pages/member/ModalID.js
  src/pages/member/ModalPassword.js
  src/pages/member/RegistMember.module.css
  src/pages/member/RegisterMember.js
  src/pages/profile/ChangePasswordModal.js
  src/pages/profile/MyProfile.js
Labels: 🌀BugFix, 💻Feature

#302 feat #26 - [출퇴근] 잔여근로시간 2분 미만일 경우 출근 제한 알림 모달 열림 기능 추가
  package-lock.json
  package.json
  src/components/Header.js
  src/components/commutes/ClockLimitModal.js
  src/components/commutes/ClockOutModal.js
  src/components/commutes/CommuteItem.js
  src/components/commutes/CommuteTime.js
  src/components/commutes/CorrectionDetailModal.js
  src/components/commutes/LimitClockInModalBy52.js
  src/css/commute/commute.css
  src/pages/commute/RecordCommute.js
Labels: 💻Feature

#305 style #3 [버튼] - 공통 컨텐츠 헤더 버튼 css 추가
  src/css/common.css
  src/css/leave/LeaveAccrual.css
  src/css/leave/MyLeave.css
  src/css/survey/SurveyList.css
  src/pages/leave/LeaveAccrual.js
  src/pages/leave/MyLeave.js
Labels: ✨Style

#308 feat #25 - [출퇴근] 잔여근로시간 8시간 이하일 경우 잔여 시간 내에 퇴근 진행 알림 모달 열림
  package-lock.json
  src/components/commutes/ClockInModal.js
  src/components/commutes/ClockLimitModal.js
  src/components/commutes/ClockOutModal.js
  src/components/commutes/ClockOutWarningModalBy52.js
  src/components/commutes/CommuteItem.js
  src/components/commutes/CommuteTime.js
  src/components/commutes/CorrectionDetailModal.js
  src/components/commutes/CorrectionUpdateModal.js
  src/components/commutes/InsertCorrectionModal.js
  src/components/commutes/LimitClockInModalBy52.js
  src/components/commutes/NewCommuteAndCorrection.js
  src/css/common.css
  src/pages/commute/CommuteManage.js
  src/pages/commute/RecordCommute.js
Labels: 💻Feature

#309 fix # 26 - [공통] 오류 수정
  src/css/common.css
  src/pages/proposal/AdminProposalPage.js
  src/pages/proposal/ProposalPage.js
Labels: 🌀BugFix

#312 feat # 11 전자결재 수정
  src/App.js
  src/components/approvals/ActionTypeModal.js
  src/components/approvals/ApprovalListComponent.js
  src/components/approvals/ApproverModal.js
  src/components/approvals/ApproverStatusConfirmModal.js
  src/components/approvals/CancelInsertModal.js
  src/components/approvals/CancelModal.js
  src/components/approvals/DeleteConfirmModal.js
  src/components/approvals/InsertConfirmModal.js
  src/components/approvals/InsertFailModal.js
  src/components/approvals/InsertSuccessModal.js
  src/components/approvals/ReturnConfirmModal.js
  src/components/approvals/TempSaveModal.js
  src/components/approvals/WarningModal.js
  src/css/approval/ApprovalDetail.module.css
  src/css/approval/ApprovalListComponent.module.css
  src/pages/approval/ApprovalInsert.js
  src/pages/approval/ApprovalTempRewrite.js
Labels: 🎈API, 🥝Refactor

#316 feat #27 - [출퇴근] 부서 수정
  src/components/commutes/CommuteTime.js
  src/pages/commute/CommuteManage.js
Labels: 🥝Refactor

#318 feat #26 [출퇴근] 날짜 수정
  src/components/Sidebar.js
  src/pages/commute/CommuteManage.js
Labels: 💻Feature
